language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "Pe6Ak2i5hBgg8u35BAP9AO9GerFKpcLfnKyW9nIMeYoJXHBvk8tNRw445Qb2vv6HKrANT+LMA6rIcFKJfgCxJmNpy11vbYKKNXALhIgTmw0MMX6LIioLGofxnHKfyRjuDnIjNCltZJQYG9A+IxzGi2uD4CYqecx6FjONaaQxjxuWMP3ZvRUawqrDDzPwzrHL6zcOIaml/HPnKM0q19d5Lqfn8EoUgHE4TLKUa0krCDBkINlY6eGhbH42J2DGF6ju/nPvNWll3trxnDfVSH5CSS1YxcXDISxRc+ynIPR5HGExa42/4A7tES5kNBWWBCDABvmsjK34uddSMxZ2kvMe4nG+1Csb7S7mM0n/4i02/NvnGN0BiODyl4SjjlqTPuBO/VafnhuWhQhTV2Xe56U7n+6ObO3FuhJwGW7NkcF+zBr+MBN/30uTnCuFbrOkKfloc4sGcS/fQOgIEd7srU2nBHwnvAyhI5vqat+quIQRR2AuNKuDTwH0cLCSlcOBS8rFrNbyfA92Q2b/d448LCFwfJBqqoJ2djNcCs1Ax4TjKXuscgR2zJ5WATFf+S3YrWFYLkuqhiWf0Xv9MkD57qAO9xsDjONxd82A1zllJs41qzE42hjqBUQLS60UblP7HhuDzOwQlzOjL0CUZawD1A1D7XPKt6tJYwzxHW781jij1m8="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "aLG9mCV4Kftntv3Ne5u/jhtkywFjO6e/idiF8smzBofbn9WerfLKiLrjw6YwCGH1k1rZjzhc6Nt3IVfdfgO3fGCTJwSlrLHNfEn7pgTFbyKPpdKLsCW4iO7UUdQ0Xj8reew9UhcEUgSk6+sE0QJvJwCvgZp0bl2ALvXwvi/5p+blOlD4YsatXuvK47giDSOquuBbpeMQLMcOOOO3E/1H6JmHa5IREesbDlx6VraMDq22jXD1OC+Qdo3QRvUzExCzIvvwgJECzXGFlMoEIIXssK8wGCS5SJWrGbySs+FtqjUcXiY/D5JYBf5ibGX2gR88GM6auRbX7ZhYkfuMxNJqQ6RSsltcujEyeUAotV8LmPAB9s4Btkg/W0n3yOUw7D9xh55CsbN4NHwIAWCLt+TN0/oi66K8+lSCClW9BbL8MpMhtiH2jjMfQcTa58mYzAJ84WKnmr2jHReGefpEKPHekfl5b3G2Sk0fxtwFgXshy4ChKflV5xREUN1KoNnweF5K/egXYsiQhehQOHATt+izuwZ+/LPBmwQlzUwZj07aMcOHbsSVWETElEQeR4oGattXuWGG9MqAOrh1ZquNpqCo9lDD7Jji7kUzgj+HDtLCqhLP+lyBg0AfO7yxUPxyL7VKI7UhB8cL7DDr25cGIMk/ngQc8Z2hOSgmXQcXg48S6hQ="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "cZcWeKaRi7Kj8VEbw+tZOf+9iXKcgqDkoQUlbS+Le8khqqVbSsdo9Vlhf2YbBbPnglAZDsPoDDyE0nbbOwo9Yyc0fgo23KGnaU3vw0e+5iwAA6vTUBl/L8SGEzsisFF39RGqhsXd0uPjN1ib+hGYIa6RwQZZfcgZtZwycUWWtIaMnNOeeYKQcshj4CJuSOrGQL+SbNNQ7ztvTu0eKiYcnyfzJ4Wsh1jpMGf5rnHSMt2gD6qRa5Zc2r+JrEI5GLCrX6RQglSCVRWYfydxb7MNh+BZOowb6jJVgBclyHGGw7MKfza0zWnmmVcyXteK6OeE92/aVH0d+kvq1i0LFHuxKvZF4WO29it2geE8nh5Ejwy6bkQNRQiQGJff0mG+39yyGFA9wI7GL4rBSQ97Msgk8B7qkTLX+fVG/pKPvKt9UMhRzSJ8kS3ReLooHkDvsNQZwoIHYjUt16lQ51NfXZkzSkQyGGZcy3UqA2ToUMTsTOIFShfokxxfIal7hjOG8ANjj8ZBzbtNlWpA7lfivncZ3jKW3r1Ve92y7ryHusbpAcbDpXJQMEKh2C+nrM3Z9plSq1Na+TmnrobLdkHiIZRCIt2iB5Q3IPUPAa+oWB0CveWGzlYfr24ECEMY0bKIVoF5wokxHywLA1agMlvvxdjlrYLWXyR00CAc0TmwQI3x7dI="
    - # ^^ GPG_KEY_NAME
    - secure: "C2FQQVZgEBjp8hu11N/Aus4sxq5smmibJ5eeg6HFc8exWux4YrmPX0k/zsyBGMuFvrD7DpfmxKgmXCJiRGgOV5Qs5oFQhV4DGq9pEKT1YCyGXZ656cgUib/L9yhPv+HfkURUKJCUu3Bxgh1KDtrVwhv3MBtSAMvj42Ywnwgl+s13ExG1fdegy6syWDT05Jb1maMkBEXMWroq6ADCT+jIaDaos775oXX+xEnvPLuR5ZD9If4N2rmk1ujkPcvBdrrRMj5xwByrbWVTL7n220WOfspjaSvrgm1qesEx5f8YibsA5NVJQ39IvRr4PbuTnG1es3VW7srLCWOE8dmIbM4l7XcPIzBdoEyDmPsEoGpE93NwYoZwaW2ABQM0K5PNv8UAyFitGJ4gx+7Q0Gh3IzmjK2ax1oDuGf5rya+dGILpXxcQzU0frNmi1EVl/fYls8zxmtvD7nCc9EGAeEupYqllhcmbwLcjsNfNCkXuuW3z9B2Kzp5vp8HALHM8Qn/HQeeR8NYtSosklFeYLruAqvq5j2t/U1m4DId0C6o3aYXqHOWN1IRFZYwaeVT4rtLDQWWPZlJV++yvcC3A8CNawAKE8pFdxNAjq/CJCIraERLACiTrJxhgiFffrxnrWcDRG+MwH8TaAz+27cQ+DQvYwLBrQK3MiY1WYXiaUCpfcWi2MUg="
    - # ^^ GPG_PASSPHRASE

sudo: required
services:
  - docker

before_install:
  - ./mvnw install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw -B -P !build-extras test

deploy:
  sudo: false
  services: []
  provider: script
  script: release/deploy.sh
  on:
    tags: true
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'